### ISSUE TITLE
What do I do after adding it? I cannot see the NoPE extension anywhere.

### ISSUE THREAD

**Issue by karan-a** [summitt/Burp-Non-HTTP-Extension#33]

**Comment by karan-a** [comment]
![image](https://user-images.githubusercontent.com/18550172/54110571-17920600-43b8-11e9-8d3b-dc2aa6bdddc0.png)

**Comment by rickespana** [comment]
If you are working with Burp branch 2.1+ it doesn't work because there are some dependency errors. There is a PR open with a solution from @jfish7 but it has not been merged because it seems the project is not being maintained anymore... You could still use NoPE extension with Burp branch 1.7 in its last release.

**Comment by ama21n** [comment]
Does anyone know the easiest way to merge @jfish7's fix? From jfish7's update on getting NoPE Burp-Non-HTTP-Extension working, what do I need to do to merge the changes and get it working... I've done the following:
1. Downloaded the latest NoPE (github.com/summitt/Burp-Non-HTTP-Extension)
2. unzipped using 'jar -xf NopeProxy.jar'
3. Cloned the fix/updates using 'git clone https://github.com/jfish7/Burp-Non-HTTP-Extension'

From here Im not too sure what to do

**Comment by 984281865DAFA** [comment]
我使用的1.7.26的版本也无法使用
![image](https://user-images.githubusercontent.com/48122587/78767028-a8bd1d00-79bc-11ea-8e07-185973df6dbb.png)
